import { PointOfInterest } from "./types";

// Points d'intérêt touristiques de la Côte de Goëlo
export const pointsOfInterest: PointOfInterest[] = [
  {
    id: "baie-st-brieuc",
    name: "Baie de Saint-Brieuc",
    description: "Réserves naturelles et paysages exceptionnels",
    latitude: 48.5147,
    longitude: -2.7642,
    type: "beach",
    icon: "🏖️",
    image: "",
  },
  {
    id: "plouha",
    name: "Côte de Goëlo - Plouha",
    description: "Falaises et sentier des douaniers",
    latitude: 48.6833,
    longitude: -2.9167,
    type: "beach",
    icon: "🏝️",
    image: "",
  },
  {
    id: "paimpol",
    name: "Paimpol",
    description: "Port de caractère et patrimoine maritime",
    latitude: 48.7833,
    longitude: -3.05,
    type: "town",
    icon: "🏰",
    image: "",
  },
  {
    id: "ile-brehat",
    name: "Île de Bréhat",
    description: "Île aux fleurs accessible en bateau",
    latitude: 48.85,
  longitude: -3,
    type: "nature",
    icon: "🌺",
    image: "",
  },
  {
    id: "saint-brieuc",
    name: "Saint-Brieuc",
    description: "Préfecture des Côtes d'Armor",
    latitude: 48.5138,
    longitude: -2.7608,
    type: "town",
    icon: "🏛️",
  },
  {
    id: "binic",
    name: "Trébeurden",
    description: "Plages de sable fin et île Milliau",
    latitude: 48.7667,
    longitude: -3.5667,
    type: "beach",
    icon: "🏖️",
  },
  {
    id: "saint-michel-en-greve",
    name: "Saint-Michel-en-Grève",
    description: "Plage de 4km et activités nautiques",
    latitude: 48.6833,
    longitude: -3.5833,
    type: "beach",
    icon: "🏄",
  },
  {
    id: "countryside-riding",
    name: "Countryside Riding",
    description: "Centre équestre et balades à cheval",
    latitude: 48.805,
    longitude: -3.295,
    type: "nature",
    icon: "🐴",
  },
  {
    id: "terrain-des-sports",
    name: "Terrain des sports",
    description: "Installations sportives locales",
    latitude: 48.81,
    longitude: -3.28,
    type: "viewpoint",
    icon: "⚽",
  },
  {
    id: "chapelle-sainte-barbe",
    name: "Chapelle Sainte-Barbe",
    description: "Chapelle historique",
    latitude: 48.774,
    longitude: -3.045,
    type: "viewpoint",
    icon: "⛪",
  },
  {
    id: "kito",
    name: "Kito",
    description: "Petit lieu local",
    latitude: 48.815,
    longitude: -3.285,
    type: "town",
    icon: "📍",
  },
  {
    id: "larboretum",
    name: "L'Arboretum",
    description: "Collection d'arbres et sentiers botaniques",
    latitude: 48.82,
    longitude: -3.29,
    type: "nature",
    icon: "🌳",
  },
  {
    id: "chapelle-saint-michel",
    name: "Chapelle Saint-Michel",
    description: "Point de vue et chapelle côtière",
    latitude: 48.783,
    longitude: -3.0667,
    type: "viewpoint",
    icon: "⛪",
  },
  // Plages
  {
    id: "anse-de-brehec",
    name: "Plage de l'anse de Bréhec",
    description: "Anse sauvage et tranquille",
    latitude: 48.792,
    longitude: -3.109,
    type: "beach",
    icon: "🏖️",
  },
  {
    id: "plage-bonaparte",
    name: "Plage Bonaparte",
    description: "Plage locale",
    latitude: 48.815,
    longitude: -3.275,
    type: "beach",
    icon: "🏖️",
  },
  {
    id: "plage-cruckin",
    name: "Plage de Cruckin",
    description: "Petite plage locale",
    latitude: 48.81,
    longitude: -3.26,
    type: "beach",
    icon: "🏝️",
  },
  // Transports
  {
    id: "train-paimpol",
    name: "Gare de Paimpol",
    description: "Ligne TER locale",
    latitude: 48.7784,
    longitude: -3.0483,
    type: "town",
    icon: "🚆",
  },
  {
    id: "train-frynaudour",
    name: "Gare Frynaudour",
    description: "Gare locale (coordonnées estimées)",
    latitude: 48.823,
    longitude: -3.292,
    type: "town",
    icon: "🚆",
  },
  // Aéroports
  {
    id: "aero-saint-brieuc",
    name: "Aéroport de Saint-Brieuc Armor",
    description: "Aéroport régional",
    latitude: 48.5378,
    longitude: -2.8544,
    type: "town",
    icon: "✈️",
  },
];
